[colors.normal]
red = "0xe56262"

[font]
size = 11

[font.normal]
family = "JetBrainsMono Nerd Font"

[shell]
args = ["new", "-A", "-s", "main"]
program = "/usr/bin/tmux"

[window]
opacity = 0.7
startup_mode = "Maximized"
