server_names = ['quad9-doh-ip4-port443-nofilter-pri', 'quad9-dnscrypt-ip4-nofilter-ecs-pri','quad9-dnscrypt-ip4-nofilter-pri','dns.digitale-gesellschaft.ch-2','libredns']
ipv4_servers = true
ipv6_servers = false
dnscrypt_servers=true
doh_servers = true
odoh_servers = false
require_nolog = true
#skip_incompatible = false
block_ipv6 = true
cache_size = 4096
cache_min_ttl = 2400
cache_max_ttl = 86400
cache_neg_min_ttl = 60
cache_neg_max_ttl = 600
[sources]
#[sources.quad9-resolvers]
#urls = ["https://quad9.net/dnscrypt/quad9-resolvers.md", "https://raw.githubusercontent.com/Quad9DNS/dnscrypt-settings/main/dnscrypt/quad9-resolvers.md"]
#minisign_key = "RWQBphd2+f6eiAqBsvDZEBXBGHQBJfeG6G+wJPPKxCZMoEQYpmoysKUN"
#cache_file = "quad9-resolvers.md"
#refresh_delay = 72
#prefix = "quad9-"
  [sources.'public-resolvers']
  urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md', 'https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md']
  cache_file = 'public-resolvers.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  refresh_delay = 72
  prefix = ''
[blocked_names]
blocked_names_file='/etc/dnscrypt-proxy/blocklist.txt'
